name: PR Comment Agent

on:
  issue_comment:
    types: [created]

permissions:
  contents: write

jobs:
  process-comment:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '@AgentSN')
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT }}

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ai-checks-1742278627
          fetch-depth: 0

      - name: Configure Git
        run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Detect Changed Files
        id: changed-files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:${{ github.event.pull_request.base.ref }}
          git diff --name-only ${{ github.event.pull_request.base.ref }} > changed_files.txt
          files=$(cat changed_files.txt | tr '\n' ' ')
          echo "files=$files" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install -r .github/scripts/requirements.txt || echo "No requirements.txt found, skipping."

      - name: Run Python Script
        run: |
          python agent.py \
            --message "${{ github.event.comment.body }}" \
            --pr_number "${{ github.event.issue.number }}" \
            --pr_branch "ai-checks-1742278627" \
            --repo "${{ github.repository }}" \
            --actor "${{ github.actor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT }}

      - name: Run styleguide enforcer script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Use GitHub secret for the API key
        run: python assistant.py "${{ env.files }}" "${{ github.event.comment.body }}"
      
      - name: Commit & Push Changes (if any)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git status  
          
          git add .
          git commit -m "Agent update from PR comment"
          git push origin "ai-checks-1742278627"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT }}
