name: OpenAI Assistant Call

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch

jobs:
  call_openai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Get the list of changed files (from the last commit)
      - name: Get list of changed files
        id: changes
        run: |
          git fetch --depth=2
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $CHANGED_FILES"
          echo "::set-output name=files::$CHANGED_FILES"


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade openai

      - name: Run OpenAI script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Use GitHub secret for the API key
        run: python openai_call.py ${{ steps.changes.outputs.files }}