name: OpenAI Assistant Call

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch

jobs:
  call_openai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_BOT }}

      # Step 2: Get the list of changed files (from the last commit)
      - name: Get list of changed files
        id: changes
        run: |
          git fetch --depth=2
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | tr '\n' ' ')
          echo "Changed files: $CHANGED_FILES"
          echo "::set-output name=files::$CHANGED_FILES"


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade openai

      - name: Run OpenAI correct grammar script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Use GitHub secret for the API key
        run: python assistant.py ${{ steps.changes.outputs.files }}
        


      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new branch
        run: git checkout -b grammar-check-bot

      - name: Commit and push changes
        run: |
          git add . -- :!pr_message.txt  # Exclude pr_message.txt from git add
          git commit -m "Grammar check task"
          git push origin grammar-check-bot
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_BOT }}
        

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ACTIONS_BOT }}
          commit-message: "Processed files and create pull request"
          branch: new-branch
          base: main
          title: "Processed files and updated"
          body: "This PR contains processed files from the GitHub Actions workflow."